;;
;; chicken-sdl2: Chicken bindings to SDL 2 (Simple DirectMedia Layer 2)
;;
;; Copyright © 2013  John Croisant.
;; All rights reserved.
;;
;; Redistribution and use in source and binary forms, with or without
;; modification, are permitted provided that the following conditions
;; are met:
;;
;; - Redistributions of source code must retain the above copyright
;;   notice, this list of conditions and the following disclaimer.
;;
;; - Redistributions in binary form must reproduce the above copyright
;;   notice, this list of conditions and the following disclaimer in
;;   the documentation and/or other materials provided with the
;;   distribution.
;;
;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;; "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;; LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
;; FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
;; COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
;; INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
;; (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
;; SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
;; HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
;; STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;; ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
;; OF THE POSSIBILITY OF SUCH DAMAGE.


(define-and-export-enum SDL_EventType
  SDL_FIRSTEVENT
  SDL_QUIT
  SDL_APP_TERMINATING
  SDL_APP_LOWMEMORY
  SDL_APP_WILLENTERBACKGROUND
  SDL_APP_DIDENTERBACKGROUND
  SDL_APP_WILLENTERFOREGROUND
  SDL_APP_DIDENTERFOREGROUND
  SDL_WINDOWEVENT
  SDL_SYSWMEVENT
  SDL_KEYDOWN
  SDL_KEYUP
  SDL_TEXTEDITING
  SDL_TEXTINPUT
  SDL_MOUSEMOTION
  SDL_MOUSEBUTTONDOWN
  SDL_MOUSEBUTTONUP
  SDL_MOUSEWHEEL
  SDL_JOYAXISMOTION
  SDL_JOYBALLMOTION
  SDL_JOYHATMOTION
  SDL_JOYBUTTONDOWN
  SDL_JOYBUTTONUP
  SDL_JOYDEVICEADDED
  SDL_JOYDEVICEREMOVED
  SDL_CONTROLLERAXISMOTION
  SDL_CONTROLLERBUTTONDOWN
  SDL_CONTROLLERBUTTONUP
  SDL_CONTROLLERDEVICEADDED
  SDL_CONTROLLERDEVICEREMOVED
  SDL_CONTROLLERDEVICEREMAPPED
  SDL_FINGERDOWN
  SDL_FINGERUP
  SDL_FINGERMOTION
  SDL_DOLLARGESTURE
  SDL_DOLLARRECORD
  SDL_MULTIGESTURE
  SDL_CLIPBOARDUPDATE
  SDL_DROPFILE
  SDL_USEREVENT
  SDL_LASTEVENT)

(define-and-export-enum SDL_eventaction
  SDL_ADDEVENT
  SDL_PEEKEVENT
  SDL_GETEVENT)
