;;
;; chicken-sdl2: Chicken bindings to SDL 2 (Simple DirectMedia Layer 2)
;;
;; Copyright © 2013  John Croisant.
;; All rights reserved.
;;
;; Redistribution and use in source and binary forms, with or without
;; modification, are permitted provided that the following conditions
;; are met:
;;
;; - Redistributions of source code must retain the above copyright
;;   notice, this list of conditions and the following disclaimer.
;;
;; - Redistributions in binary form must reproduce the above copyright
;;   notice, this list of conditions and the following disclaimer in
;;   the documentation and/or other materials provided with the
;;   distribution.
;;
;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;; "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;; LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
;; FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
;; COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
;; INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
;; (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
;; SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
;; HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
;; STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;; ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
;; OF THE POSSIBILITY OF SUCH DAMAGE.


(define-and-export-enum unsigned-int8
  SDL_ALPHA_OPAQUE
  SDL_ALPHA_TRANSPARENT)


(define-and-export-enum SDL_PixelTypeEnum
  SDL_PIXELTYPE_UNKNOWN
  SDL_PIXELTYPE_INDEX1
  SDL_PIXELTYPE_INDEX4
  SDL_PIXELTYPE_INDEX8
  SDL_PIXELTYPE_PACKED8
  SDL_PIXELTYPE_PACKED16
  SDL_PIXELTYPE_PACKED32
  SDL_PIXELTYPE_ARRAYU8
  SDL_PIXELTYPE_ARRAYU16
  SDL_PIXELTYPE_ARRAYU32
  SDL_PIXELTYPE_ARRAYF16
  SDL_PIXELTYPE_ARRAYF32)

(define-and-export-enum SDL_BitmapOrderEnum
  SDL_BITMAPORDER_NONE
  SDL_BITMAPORDER_4321
  SDL_BITMAPORDER_1234)

(define-and-export-enum SDL_PackedOrderEnum
  SDL_PACKEDORDER_NONE
  SDL_PACKEDORDER_XRGB
  SDL_PACKEDORDER_RGBX
  SDL_PACKEDORDER_ARGB
  SDL_PACKEDORDER_RGBA
  SDL_PACKEDORDER_XBGR
  SDL_PACKEDORDER_BGRX
  SDL_PACKEDORDER_ABGR
  SDL_PACKEDORDER_BGRA)

(define-and-export-enum SDL_ArrayOrderEnum
  SDL_ARRAYORDER_NONE
  SDL_ARRAYORDER_RGB
  SDL_ARRAYORDER_RGBA
  SDL_ARRAYORDER_ARGB
  SDL_ARRAYORDER_BGR
  SDL_ARRAYORDER_BGRA
  SDL_ARRAYORDER_ABGR)

(define-and-export-enum SDL_PackedLayoutEnum
  SDL_PACKEDLAYOUT_NONE
  SDL_PACKEDLAYOUT_332
  SDL_PACKEDLAYOUT_4444
  SDL_PACKEDLAYOUT_1555
  SDL_PACKEDLAYOUT_5551
  SDL_PACKEDLAYOUT_565
  SDL_PACKEDLAYOUT_8888
  SDL_PACKEDLAYOUT_2101010
  SDL_PACKEDLAYOUT_1010102)


(define-and-export-enum SDL_PixelFormatEnum
  SDL_PIXELFORMAT_UNKNOWN
  SDL_PIXELFORMAT_INDEX1LSB
  SDL_PIXELFORMAT_INDEX1MSB
  SDL_PIXELFORMAT_INDEX4LSB
  SDL_PIXELFORMAT_INDEX4MSB
  SDL_PIXELFORMAT_INDEX8
  SDL_PIXELFORMAT_RGB332
  SDL_PIXELFORMAT_RGB444
  SDL_PIXELFORMAT_RGB555
  SDL_PIXELFORMAT_BGR555
  SDL_PIXELFORMAT_ARGB4444
  SDL_PIXELFORMAT_RGBA4444
  SDL_PIXELFORMAT_ABGR4444
  SDL_PIXELFORMAT_BGRA4444
  SDL_PIXELFORMAT_ARGB1555
  SDL_PIXELFORMAT_RGBA5551
  SDL_PIXELFORMAT_ABGR1555
  SDL_PIXELFORMAT_BGRA5551
  SDL_PIXELFORMAT_RGB565
  SDL_PIXELFORMAT_BGR565
  SDL_PIXELFORMAT_RGB24
  SDL_PIXELFORMAT_BGR24
  SDL_PIXELFORMAT_RGB888
  SDL_PIXELFORMAT_RGBX8888
  SDL_PIXELFORMAT_BGR888
  SDL_PIXELFORMAT_BGRX8888
  SDL_PIXELFORMAT_ARGB8888
  SDL_PIXELFORMAT_RGBA8888
  SDL_PIXELFORMAT_ABGR8888
  SDL_PIXELFORMAT_BGRA8888
  SDL_PIXELFORMAT_ARGB2101010
  SDL_PIXELFORMAT_YV12
  SDL_PIXELFORMAT_IYUV
  SDL_PIXELFORMAT_YUY2
  SDL_PIXELFORMAT_UYVY
  SDL_PIXELFORMAT_YVYU)
