
(define-and-export-enum SDL_WindowFlags
  SDL_WINDOW_FULLSCREEN
  SDL_WINDOW_FULLSCREEN_DESKTOP
  SDL_WINDOW_OPENGL
  SDL_WINDOW_SHOWN
  SDL_WINDOW_HIDDEN
  SDL_WINDOW_BORDERLESS
  SDL_WINDOW_RESIZABLE
  SDL_WINDOW_MINIMIZED
  SDL_WINDOW_MAXIMIZED
  SDL_WINDOW_INPUT_GRABBED
  SDL_WINDOW_INPUT_FOCUS
  SDL_WINDOW_MOUSE_FOCUS
  SDL_WINDOW_FOREIGN)


(define-and-export-enum SDL_WindowEventID
  SDL_WINDOWEVENT_NONE
  SDL_WINDOWEVENT_SHOWN
  SDL_WINDOWEVENT_HIDDEN
  SDL_WINDOWEVENT_EXPOSED
  SDL_WINDOWEVENT_MOVED
  SDL_WINDOWEVENT_RESIZED
  SDL_WINDOWEVENT_SIZE_CHANGED
  SDL_WINDOWEVENT_MINIMIZED
  SDL_WINDOWEVENT_MAXIMIZED
  SDL_WINDOWEVENT_RESTORED
  SDL_WINDOWEVENT_ENTER
  SDL_WINDOWEVENT_LEAVE
  SDL_WINDOWEVENT_FOCUS_GAINED
  SDL_WINDOWEVENT_FOCUS_LOST
  SDL_WINDOWEVENT_CLOSE)
